### ISSUE TITLE
Is it possible to set it to auto-turn off?

### ISSUE THREAD

**Issue by martixy** [PhilGrayson/chrome-csp-disable#11]
Like, maybe set a period, or automatically turn off when closing chrome?

People are forgetful and easily distracted. That doesn't go well with security. :)

**Comment by rdsedmundo** [comment]
Chrome has an option to allow the extension to change the site behavior only when you click it.

`Right-click in the Icon -> This site can read and change site data -> When you click the extension`

Note that it requires a reload of the page once you click in order to it to work properly.

**Comment by PhilGrayson** [comment]
Hi,
I've submitted a new version of this extension for review. It will disable Content-Security-Policy header per tab instead of globally.

The review may take a while though. This is the message I got:
> Because of the following issue, your extension may require an in-depth review:
> - Broad Host Permissions
> Instead of requesting broad host permissions, consider using the activeTab permission, or specify the sites that your extension needs access to. Both options are more secure than allowing full access to an indeterminate number of sites, and they may help minimize review times.

I'll have a think if I can incorporate activeTab permission instead of granting this extension access to `http://*/*` and `https://*/*`.

**Comment by PhilGrayson** [comment]
Hope that change is good enough :)
